version: '3.0'

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT": "14"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      DATABASE_URL: &DATABASE_URL "mongodb://mongo:27017/ros"
      S3_ENDPOINT: &S3_ENDPOINT "minio"
      S3_PORT: &S3_PORT 9000
      S3_ACCESS_KEY: &S3_ACCESS_KEY "ros"
      S3_SECRET_KEY: &S3_SECRET_KEY "ciscocisco"
      FIREBASE: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicm9zLWNsb3VkLWNjNzExIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNzljMjlkMDIxY2Y3NzZmMDE3NjBlZTAyODE5ZWU2NzY1N2RjNzBmYyIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDOU9aaG5CQ3Z2RHEvQ1xuUE03bFE1eCtqREQvWVpnZ1lJdU1VQWRQbVRZMEwrSUNpOVZaNGphN2U0NFF3d2g1dGNqbUhmNC9MVDBVMEdJbVxuK3dIRlAzK0sxVmFwTzhGeXJkT1hESmt5Mmt2VUM3R1NQbnFKRWdQMTdnbUhSeXIvckV6WldnRUk5VmJ6Y0duWVxuZG9jbXIwU0FXLzRHMnlWbUhWMXgzTHZDVkhGYkZjcm9zbDRib1NPQXFFNGIzWVNRWUsyOGZjRWFkTGIxeERaSFxubVZ3QUtDVnFxa3Q2YVU0QytnTUl0K0M1RmJoR3JpbXBGTnFoRU1MV2ZIbUptdSsrRUJlYVExSjQ5U2hPbWNhVVxuSWxyb084SzJjWTJKVDVGVUpQSkEyb2dSQklMdXo3SHFhZlpJdWJTVTJMNTFvb0VpUlFuTm1SWExrU3pYbWphRFxuVktuc3ZqMUJBZ01CQUFFQ2dnRUFENWhUMW1lcVhFY3NWcGlPMzZmSkdjZmhrT2FnOUVnb3NCMTNZTWpLaGhZTlxuTFRNTG1COFQ3ak15WS9EQy9jN3MyZ1JPVERRbEJOWmd4SUFxNXZBRENiVG44Y1ltUFJhVTZlM0VvWU9Ldk5UaVxuNDEvcFZ1c29idWdabW0vVDNDTDk2V3JveTIxMjUxVFVNRjRpYU42SWlZQ3JhTEsrZkJJKy9ZK1kzTno3UTZ1ZFxuaFRwVll1Q21WeUs4czRVeDJUTGVxckdHWC9TZTJOb05URy8zSGUyUGpZam5pOGZGeTNLejNleTYvRnQ4TXFsRFxuZCtHak5aai9Ga2FUeDRWSmx4SklqTDlHT1M3Q3hDeXB5NzZvY1JCWFZTc0pFZHN2d1hRbEhEUDROWW92TU1mblxuMDUvOWxPYVRIMzVta2lLTG1ERHUrTzZvR0ZKWTVBMWxxSVF6RU5nUjNRS0JnUURxcmJKdmRxd2JmdUhMeGFCelxuQ0ZIUWJtWGRrZmkzNHVQUWVYVS9jakYra3Z1cFN1dDJuMXlvNmw5ZG1PVEdtMG11T016a3EzcVZ5RlIzSG90aFxuMzhSeDBMcUM3TVFHNnd0U1ZwOFlXU2l6ZEw2SFoveFBrNkR0MFpHeDhTTHRtWExNNWtFNHA3eVdlclNTV3hmdlxubk5YZ3R2akx2YzhyU2dCUTlVTGZpU2RPWFFLQmdRRE9hcllQT0NzMCtQM1hJUFZCMjNFV2pwUTAxN2cyQi8zMFxuUG04MWFEMUYrTFVvbDlIWkZiNFFlR1QxUUpCNEN4WjJKYU4zbHRyblo3cE95dnpzRUVmeDU0dHhVRTZwSzhBZ1xuZnNHUXpNVnQzQWRDaExRU0U0OFgzTk5rYUg5Zy9Ga0ozWk5FS3phSmlPVFA0V0FzWGJQc3kyenlIMTVNTHY3K1xud3huYkhpN1VOUUtCZ1FDOG1vZ3pLSTY5TWtYSmZMU3NmbDB5UStjK0lSaGd3TW9TTytyTTZMdDZYQ3BCTG1MNlxuWEswZFcrNzB5L0hnNCtCZFVtem93aCtzek9tRktsa2VlYlhwT3JVS2o3b2pUVGMySDBPUlQrWjBBemswblkrYlxuYkt3RE5WQUFVQ21nQnBqS3I2cHZHKzltaUlzaXJHOGFOVk4yVzlhcjk0bk40cFZLZXpJWmNLTFVTUUtCZ0dYNlxuZm52Q2FrWS9oVmxWWlJYbVRsYXdsalFOSjJzNlE1TDVqWU83UGhwbHAwcW94dm9UTGRXQlJZK05HRkxXVjRDRFxuVStGdlhETGJJa1p2THNtSnVhR2ZuVnFjTEdDVHh0WEhDZVo1NUVoRVhpblUyZ25jTStPOEs0djl2SUN6NjJGZVxuWUxWYkRCU2kxemlFeGpqbENsRkFwMUJ2Z3V6c2d2cG1kVTIxK2JqSkFvR0JBSlVFRDBvQnM0dGlqano1YjRlY1xuZVhmUzVxUzJOanp3cUx5SHQzQW9keWlTc0RqRUhkZTdOOXRRTU9UaFhKMklTanlOajdZOTlxY1BFZFNOdDhWd1xuOEtXZHYzMlJQOE52bklQZmV1QVVlOEtQV01TOFprdmNqRTlDSDYvNzJDcVR1RWVvSktFSUhZNGdCbGZ5ZmI5U1xuTjRmbTBoZHVLd2ZpRDgrdXpKN2R0T3hRXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGstdWxveXpAcm9zLWNsb3VkLWNjNzExLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExMDQyNjQ1MjI4OTcwMzE0OTUwMiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmlyZWJhc2UtYWRtaW5zZGstdWxveXolNDByb3MtY2xvdWQtY2M3MTEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0="
      ELASTIC_URL: &ELASTIC_URL "http://elastic:9200"
      ELASTIC_INDEX: &ELASTIC_INDEX "ros"
      DEV: "true"
    depends_on:
      - mongo
      - minio
      - elastic

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: *S3_ACCESS_KEY
      MINIO_SECRET_KEY: *S3_SECRET_KEY
    command: server /data
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000

  elastic:
    image: elasticsearch:7.9.2
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "node.name=elastic"
      - "bootstrap.memory_lock=true"
    volumes:
    - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  mongo-data:
  minio-data:
  elastic-data: